"""Connected Healer and Crystal one-to-many relationship

Revision ID: b0f0759f37c8
Revises: 5dd069dbbf35
Create Date: 2023-05-09 10:17:08.118744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f0759f37c8'
down_revision = '5dd069dbbf35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crystal', sa.Column('healer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crystal', 'healer', ['healer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crystal', type_='foreignkey')
    op.drop_column('crystal', 'healer_id')
    # ### end Alembic commands ###
